spring:
  application:
    name: spring-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
